### Import library yang dibutuhkan untuk visualisasi data maupun model processingnya

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, normalize, StandardScaler
from sklearn import metrics
import statsmodels.api as sm

### Membaca data CSV 

In [2]:
df = pd.read_csv("bank-additional-full.csv", sep=';')
df.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

### Menampilkan data info dan melihat data apakah terdapat data null di dalamnya

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [4]:
df.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [5]:
df.rename(columns={"default":"credit", "y":"subscribed"}, inplace=True)

In [6]:
df['subscribed'].replace({'yes':1, 'no':0}, inplace=True)

In [7]:
corr = df.corr()
print(corr['subscribed'].sort_values(axis=0, ascending=True))

nr.employed      -0.354678
pdays            -0.324914
euribor3m        -0.307771
emp.var.rate     -0.298334
cons.price.idx   -0.136211
campaign         -0.066357
age               0.030399
cons.conf.idx     0.054878
previous          0.230181
duration          0.405274
subscribed        1.000000
Name: subscribed, dtype: float64


### Menghapus feature yang tidak dibutuhkan

In [8]:
# drop features yang memiliki korelasi lebih sedikit dan tidak relevan dengan proses klasifikasi
df.drop(columns=['nr.employed','pdays','euribor3m','emp.var.rate',
    'cons.price.idx','day_of_week','cons.conf.idx','contact','month'],axis=0, inplace=True)

In [9]:
df

age          job  marital            education   credit housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

       duration  campaign  previous     poutcome  subscribed  
0           261         1         0  nonexistent           0  
1           149         1         0  nonexistent           0  
2           226         1         0  nonexistent           0  
3           151         1         0  nonexistent           0  
4           307         1         0  nonexistent           0  
...         ...       ...       ...          ...         ...  
41183       334         1         0  nonexistent           1  
41184       383         1         0  nonexistent           0  
41185       189         2         0  nonexistent           0  
41186       442         1         0  nonexistent           1  
41187       239         3         1      failure           0  

[41188 rows x 12 columns]

In [10]:
encoder = LabelEncoder()
col = ['marital','credit','housing','loan']

for i in col:
    df[i] = encoder.fit_transform(df[i])

In [11]:
# Encoding
cat_features = ['job','marital','education','credit','housing','loan','poutcome']
df = pd.get_dummies(df, columns=cat_features, drop_first=True)
df

age  duration  campaign  previous  subscribed  job_blue-collar  \
0       56       261         1         0           0                0   
1       57       149         1         0           0                0   
2       37       226         1         0           0                0   
3       40       151         1         0           0                0   
4       56       307         1         0           0                0   
...    ...       ...       ...       ...         ...              ...   
41183   73       334         1         0           1                0   
41184   46       383         1         0           0                1   
41185   56       189         2         0           0                0   
41186   44       442         1         0           1                0   
41187   74       239         3         1           0                0   

       job_entrepreneur  job_housemaid  job_management  job_retired  ...  \
0                     0              1               0            0  ...   
1                     0              0               0            0  ...   
2                     0              0               0            0  ...   
3                     0              0               0            0  ...   
4                     0              0               0            0  ...   
...                 ...            ...             ...          ...  ...   
41183                 0              0               0            1  ...   
41184                 0              0               0            0  ...   
41185                 0              0               0            1  ...   
41186                 0              0               0            0  ...   
41187                 0              0               0            1  ...   

       education_university.degree  education_unknown  credit_1  credit_2  \
0                                0                  0         0         0   
1                                0                  0         1         0   
2                                0                  0         0         0   
3                                0                  0         0         0   
4                                0                  0         0         0   
...                            ...                ...       ...       ...   
41183                            0                  0         0         0   
41184                            0                  0         0         0   
41185                            1                  0         0         0   
41186                            0                  0         0         0   
41187                            0                  0         0         0   

       housing_1  housing_2  loan_1  loan_2  poutcome_nonexistent  \
0              0          0       0       0                     1   
1              0          0       0       0                     1   
2              0          1       0       0                     1   
3              0          0       0       0                     1   
4              0          0       0       1                     1   
...          ...        ...     ...     ...                   ...   
41183          0          1       0       0                     1   
41184          0          0       0       0                     1   
41185          0          1       0       0                     1   
41186          0          0       0       0                     1   
41187          0          1       0       0                     0   

       poutcome_success  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
...                 ...  
41183                 0  
41184                 0  
41185                 0  
41186                 0  
41187                 0  

[41188 rows x 34 columns]

In [12]:
#Assign variable features dan label
X = df.drop(columns='subscribed', axis=1).values
y = df['subscribed'].values

### Data scaling

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=103)


In [14]:
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.fit_transform(X_test)

### Logistik Regression

In [15]:
from sklearn.linear_model import LogisticRegression
model_lr = LogisticRegression()
model_lr.fit(X_train, y_train)
ypred = model_lr.predict(X_test)
print("Accuracy: ",metrics.accuracy_score(y_test, ypred))
print(metrics.confusion_matrix(y_test, ypred))
print(metrics.classification_report(y_test, ypred))

Accuracy:  0.9076636724123979
[[10731   238]
 [  903   485]]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95     10969
           1       0.67      0.35      0.46      1388

    accuracy                           0.91     12357
   macro avg       0.80      0.66      0.70     12357
weighted avg       0.89      0.91      0.89     12357



### Support Vector Machine

In [16]:
from sklearn import svm
svm_model = svm.SVC()
svm_model.fit(X_train, y_train)
ypred2=svm_model.predict(X_test)
print("Acc: ", metrics.accuracy_score(y_test, ypred2))
print(metrics.confusion_matrix(y_test, ypred2))
print(metrics.classification_report(y_test, ypred2))

Acc:  0.902889050740471
[[10801   168]
 [ 1032   356]]
              precision    recall  f1-score   support

           0       0.91      0.98      0.95     10969
           1       0.68      0.26      0.37      1388

    accuracy                           0.90     12357
   macro avg       0.80      0.62      0.66     12357
weighted avg       0.89      0.90      0.88     12357



### K-Nearest Neighbor

In [17]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier()
KNN.fit(X_train, y_train)
pred_cv5= KNN.predict(X_test)
print("ACC: ", metrics.accuracy_score(y_test, pred_cv5))
matrix5 = metrics.confusion_matrix(y_test, pred_cv5)
print(matrix5)
print(metrics.classification_report(y_test, pred_cv5))

ACC:  0.8952011005907583
[[10654   315]
 [  980   408]]
              precision    recall  f1-score   support

           0       0.92      0.97      0.94     10969
           1       0.56      0.29      0.39      1388

    accuracy                           0.90     12357
   macro avg       0.74      0.63      0.66     12357
weighted avg       0.88      0.90      0.88     12357



### Naive Bayes

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print("Number of mislabeled points out of a total %d points : %d"
% (X_test.shape[0], (y_test != y_pred).sum()))

Number of mislabeled points out of a total 20594 points : 3333


In [19]:
from sklearn.metrics import accuracy_score
accuracy= accuracy_score(y_test, y_pred)
print("Akurasi Naive Bayes : ",accuracy)

Akurasi Naive Bayes :  0.8381567446829173


In [20]:
# Menghitung nilai akurasi dari klasifikasi naive bayes 
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.88      0.91     18291
           1       0.35      0.51      0.42      2303

    accuracy                           0.84     20594
   macro avg       0.64      0.70      0.66     20594
weighted avg       0.87      0.84      0.85     20594



### Random Forest

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
clf = RandomForestClassifier()
y_pred = clf.fit(X_train, y_train).predict(X_test)

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94     18291
           1       0.59      0.34      0.43      2303

    accuracy                           0.90     20594
   macro avg       0.75      0.66      0.69     20594
weighted avg       0.88      0.90      0.89     20594



### Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[17738,   553],
       [ 1515,   788]], dtype=int64)